 
version: '3.3'

services:
  postgres-db:
    image: postgres
    networks: 
      - prox
      - user-profile-db
    volumes: 
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=user-profile-service
      - POSTGRES_USER=user-profile-service
      - POSTGRES_DB=user-profile-db
      - PGDATA=/var/lib/postgresql/data/pgdata

    ports:
      - 5432:5432

volumes:
 db-data:
    driver: local

networks:
  prox:
    external: true
  user-profile-db: